version: '3.9'

services:
  rebase-labs:
    container_name: rebaselabs
    image: ruby
    working_dir: /app
    volumes:
      - .:/app
      - ./gems:/usr/local/bundle
    command: bash -c "bundle && ruby server.rb"
    ports:
     - "3000:3000" 
    depends_on:
     - postgresdb
  
  postgresdb:
    container_name: postgreesdb
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes: 
    - ./postgres-data:/var/lib/postgresql/data
