#!/bin/bash

docker network create rebaselabs-network

docker run \
  --rm \
  --name postgresdb \
  -e POSTGRES_USER=admin \
  -e POSTGRES_PASSWORD=admin \
  -v $(pwd)/postgres-data-rebaselabs:/var/lib/postgresq/data \
  --network rebaselabs-network \
  postgres